version: '3.5'
services:
  xxxxxxxxxx:   
    image: redis:6.0
    container_name:  xxxxxxxxxx
    restart: always    
    ports:
      - 6000:6379
    volumes:
      - ./redis_data:/data
      - ./redis_config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass  xxxxxxxxxx --appendonly yes

  #  xxxxxxxxxx:
  #   image:  xxxxxxxxxx
  #   # container_name:  xxxxxxxxxx
  #   restart: always
  #   depends_on:
  #     -  xxxxxxxxxx
  #   # ports:
  #   #   - 8883:8883

networks:
  default:
    external: 
      name:  xxxxxxxxxx
