
version: '3.5'
services:
  ru-smart-caching:   
    image: redis:6.0
    container_name: ru-smart-caching
    restart: always    
    ports:
      - 6000:6379
    volumes:
      - ./redis_data:/data
      - ./redis_config/redis.conf:/redis.conf
    command: redis-server /redis.conf --requirepass admin-ru-smart-caching --appendonly yes


  # ru-smart-api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
    # image: charandetkrathok/ru-smart-api:0.6
    # container_name: ru-smart-api
    # restart: always
    # depends_on:
    #   - ru-smart-caching
    # ports:
    #   - 8883:8883

networks:
  default:
    external: 
      name: backend-services

    
# docker-compose up --scale ru-smart-api=3