ruSmart: 
  port: ":xxx"

db: 
  openDriver: "godror"
  connection: 
    "user=\"xxx\" 
     password=\"xxxx#\" 
     connectString=\"xxxx?expire_timconnect_time=2\"
     sysdba=0
     sysoper=0
     poolMinSessions=1
     poolMaxSessions=1000
     poolIncrement=1
     standaloneConnection=0
     enableEvents=0
     heterogeneousPool=0
     externalAuth=0
     prelim=0
     poolWaitTimeout=5m
     poolSessionMaxLifetime=1h
     poolSessionTimeout=30s
     timezone=\"local\""
 
redis_cache:
  addressLocal: "localhost:6000" xxxx
  address: "xxxx"
  password: "xxxx"
  db-num: 0

token: 
  issuer: "xxxx"
  secretKey: "xxxx"
