ruSmart: 
  port: ":xxxxxxxx"

db: 
  openDriver: "godror"
  connection: 
    "user=\"xxxxxxxx\" 
     password=\"xxxxxxxx\" 
     connectString=\"xxxxxxxx?expire_timconnect_time=2\"
     sysdba=0
     sysoper=0
     poolMinSessions=1
     poolMaxSessions=1000
     poolIncrement=1
     standaloneConnection=0
     enableEvents=0
     heterogeneousPool=0
     externalAuth=0
     prelim=0
     poolWaitTimeout=5m
     poolSessionMaxLifetime=1h
     poolSessionTimeout=30s
     timezone=\"local\""
 
redis_cache:
  addressLocal: "localhost:xxxxxxxx" 
  # addressLocal: "127.0.0.1:xxxxxxxx" 
  address: "xxxxxxxx:6379"
  password: "xxxxxxxx"
  db-num: 0

token: 
  issuer: "xxxxxxxx"
  secretKey: "xxxxxxxx"
