ruConnext: 
  port: ":8883"

db: 
  openDriver: " xxxxxxxxxx"
  connection: 
    "user=\" xxxxxxxxxx\" 
     password=\" xxxxxxxxxx#\" 
     connectString=\"1 xxxxxxxxxx?expire_timconnect_time=2\"
     sysdba=0
     sysoper=0
     poolMinSessions=1
     poolMaxSessions=1000
     poolIncrement=1
     standaloneConnection=0
     enableEvents=0
     heterogeneousPool=0
     externalAuth=0
     prelim=0
     poolWaitTimeout=5m
     poolSessionMaxLifetime=1h
     poolSessionTimeout=30s
     timezone=\"local\""
 
redis_cache:
  addressInLocal: "localhost:6000" 
  addressInContainer: " xxxxxxxxxx:6379"
  addressInServer: " xxxxxxxxxx:6000"
  password: " xxxxxxxxxx"
  db-num: 0

token: 
  issuer: " xxxxxxxxxx"
  secretKey: " xxxxxxxxxx"

